import fs from 'fs';

const content = fs.readFileSync('src/App.tsx', 'utf-8');

const lines = content.split('\n');
const newLines = lines.filter(line => {
  if (line.includes('const [isSettingsOpen, setIsSettingsOpen] = useState(false);')) return false;
  if (line.includes('const [tempSettings, setTempSettings] = useState({')) return false;
  if (line.includes('apiKey: \'\',')) return false;
  if (line.includes('temperature: 0.7,')) return false;
  if (line.includes('theme: \'light\' as \'light\' | \'dark\',')) return false;
  if (line.includes('bgImage: null as string | null,')) return false;
  if (line.includes('promptTemplates: [] as PromptTemplate[],')) return false;
  if (line.includes('storyTemplates: [] as PromptTemplate[],')) return false;
  if (line.includes('useTieredMemory: true,')) return false;
  if (line.includes('isPaintingEnabled: false,')) return false;
  if (line.includes('paintingProvider: \'jimeng\',')) return false;
  if (line.includes('paintingApiKey: \'\',')) return false;
  if (line.includes('quickGenerate: false')) return false;
  if (line.includes('const handleOpenSettings = () => {')) return false;
  if (line.includes('setTempSettings({')) return false;
  if (line.includes('apiKey,')) return false;
  if (line.includes('temperature,')) return false;
  if (line.includes('theme: globalTheme,')) return false;
  if (line.includes('bgImage,')) return false;
  if (line.includes('promptTemplates,')) return false;
  if (line.includes('storyTemplates,')) return false;
  if (line.includes('useTieredMemory,')) return false;
  if (line.includes('isPaintingEnabled,')) return false;
  if (line.includes('paintingProvider,')) return false;
  if (line.includes('paintingApiKey,')) return false;
  if (line.includes('quickGenerate')) return false;
  if (line.includes('});')) return false;
  if (line.includes('setBalance(null);')) return false;
  if (line.includes('setBalanceError(null);')) return false;
  if (line.includes('setActiveSettingsTab(\'api\');')) return false;
  if (line.includes('setIsSettingsOpen(true);')) return false;
  if (line.includes('setSidebarOpen(false);')) return false;
  if (line.includes('const handleSaveSettings = async () => {')) return false;
  if (line.includes('setApiKey(tempSettings.apiKey);')) return false;
  if (line.includes('setTemperature(tempSettings.temperature);')) return false;
  if (line.includes('setUseTieredMemory(tempSettings.useTieredMemory);')) return false;
  if (line.includes('setIsPaintingEnabled(tempSettings.isPaintingEnabled);')) return false;
  if (line.includes('setPaintingProvider(tempSettings.paintingProvider);')) return false;
  if (line.includes('setPaintingApiKey(tempSettings.paintingApiKey);')) return false;
  if (line.includes('setQuickGenerate(tempSettings.quickGenerate);')) return false;
  if (line.includes('api.saveSettings({')) return false;
  if (line.includes('apiKey: tempSettings.apiKey,')) return false;
  if (line.includes('temperature: tempSettings.temperature,')) return false;
  if (line.includes('theme,')) return false;
  if (line.includes('useTieredMemory: tempSettings.useTieredMemory,')) return false;
  if (line.includes('isPaintingEnabled: tempSettings.isPaintingEnabled,')) return false;
  if (line.includes('paintingProvider: tempSettings.paintingProvider,')) return false;
  if (line.includes('paintingApiKey: tempSettings.paintingApiKey,')) return false;
  if (line.includes('quickGenerate: tempSettings.quickGenerate')) return false;
  if (line.includes('}).catch(console.error);')) return false;
  if (line.includes('setIsSettingsOpen(false);')) return false;
  if (line.includes('const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {')) return false;
  if (line.includes('const file = e.target.files?.[0];')) return false;
  if (line.includes('if (file) {')) return false;
  if (line.includes('const reader = new FileReader();')) return false;
  if (line.includes('reader.onloadend = async () => {')) return false;
  if (line.includes('const result = reader.result as string;')) return false;
  if (line.includes('setBgImage(result);')) return false;
  if (line.includes('setTempSettings(prev => ({ ...prev, bgImage: result }));')) return false;
  if (line.includes('await api.saveSettings({')) return false;
  if (line.includes('bgImage: result,')) return false;
  if (line.includes('reader.readAsDataURL(file);')) return false;
  if (line.includes('const fetchBalance = async () => {')) return false;
  if (line.includes('if (!tempSettings.apiKey) {')) return false;
  if (line.includes('setBalanceError(\'请先输入 API Key\');')) return false;
  if (line.includes('return;')) return false;
  if (line.includes('try {')) return false;
  if (line.includes('const data = await api.getBalance(tempSettings.apiKey);')) return false;
  if (line.includes('setBalance(data);')) return false;
  if (line.includes('} catch (e: any) {')) return false;
  if (line.includes('setBalanceError(e.message || \'查询失败\');')) return false;
  
  return true;
});

// fs.writeFileSync('src/App.tsx', newLines.join('\n'));
